#pragma once
#include "common/glob.h"

enum OUTGAME_MODE
{
    OUTGAME_MODE_INIT = 0,
    OUTGAME_MODE_WAIT = 1,
    OUTGAME_MODE_LOGO = 2,
    OUTGAME_MODE_TITLE_TOP = 3,
    OUTGAME_MODE_TITLE = 4,
    OUTGAME_MODE_ALBUM = 5,
    OUTGAME_MODE_BATTLE = 6,
    OUTGAME_MODE_OPTION = 7,
    OUTGAME_MODE_MODESEL = 8,
    OUTGAME_MODE_MAP_DATA_EDIT = 9,
    OUTGAME_MODE_SOUND_TEST = 10,
    OUTGAME_MODE_SCENE_TEST = 11,
    OUTGAME_MODE_MOTION_TEST = 12,
    OUTGAME_MODE_ROOM_SIZE_CHECK = 13,
    OUTGAME_MODE_LAYOUT_TEST = 14,
    OUTGAME_MODE_DBG_MAX = 9,
    OUTGAME_MODE_DBG_STORY_MODE = 5
};

OUTGAME_WRK outgame_wrk;