#pragma once

enum
{
    INGAME_MODE_FIRST_LOAD = 0,
    INGAME_MODE_INIT = 1,
    INGAME_MODE_WAIT = 2,
    INGAME_MODE_NEW_GAME = 3,
    INGAME_MODE_LOAD_START = 4,
    INGAME_MODE_MSN_TITLE = 5,
    INGAME_MODE_NOMAL = 6,
    INGAME_MODE_EVENT = 7,
    INGAME_MODE_SPECIAL_EVENT = 8,
    INGAME_MODE_AREA_MOVE = 9,
    INGAME_MODE_MENU = 10,
    INGAME_MODE_PAUSE = 11,
    INGAME_MODE_SPD_MAP = 12,
    INGAME_MODE_SPD_OPT = 13,
    INGAME_MODE_GET_ITEM = 14,
    INGAME_MODE_WANDER_SOUL = 15,
    INGAME_MODE_SAVE_POINT = 16,
    INGAME_MODE_PHOTO_AFTER = 17,
    INGAME_MODE_GHOST_DEAD = 18,
    INGAME_MODE_SGST_DISP = 19,
    INGAME_MODE_GAME_OVER = 20,
    INGAME_MODE_GAME_OVER_ALBUM = 21,
    INGAME_MODE_INTER_MSN = 22,
    INGAME_MODE_ENDING = 23,
    INGAME_MODE_WAIT_MSN0 = 24
};

extern void InGameInit();
extern void InGameCtrl();